pages:
  - Home: 'index.md'
  - Getting Started:
    - Installation: 'getting_started/installation.md'
    - Basics:
        - Terminology: 'getting_started/basics/terminology.md'
        - Workflow TypeScript: 'getting_started/basics/workflow_ts.md'
        - Workflow JavaScript: 'getting_started/basics/workflow_js.md'
        - Exposing Components: 'getting_started/basics/exposing_components.md'
        - Config Serializations: 'getting_started/basics/config_serializations.md'
  - Configuration:
    - General: 'configuration/general.md'
    - Modules: 'configuration/modules.md'
    - Components:
      - General: 'configuration/components/general.md'
      - Parameters: 'configuration/components/parameters.md'
      - Default Values: 'configuration/components/default_values.md'
      - Inherited Values: 'configuration/components/inherited_values.md'
      - Object Mapping: 'configuration/components/object_mapping.md'
      - Entry Collection: 'configuration/components/entry_collection.md'
    - Configurations:
      - General: 'configuration/configurations/general.md'
      - Semantic: 'configuration/configurations/semantic.md'
      - Non-Semantic: 'configuration/configurations/nonsemantic.md'
      - Variables: 'configuration/configurations/variables.md'
  - Loading:
    - ComponentsManager: 'loading/manager.md'
    - Registration: 'loading/registration.md'
    - Instantiation: 'loading/instantiation.md'
  - Compilation: 'compilation.md'
  - Comparison: 'comparison.md'
  - Example: 'example.md'

site_name: Components.js Documentation

markdown_extensions:
  - admonition

theme: readthedocs
