pages:
  - Home: 'index.md'
  - Getting Started:
    - Installation: 'getting_started/installation.md'
    - Basics:
        - Home: 'getting_started/basics/home.md'
        - Terminology: 'getting_started/basics/terminology.md'
        - Workflow: 'getting_started/basics/workflow.md'
        - Exposing Components: 'getting_started/basics/exposing_components.md'
        - Config Serializations: 'getting_started/basics/config_serializations.md'
  - Configuration:
    - General: 'configuration/general.md'
    - Modules: 'configuration/modules.md'
    - Components:
      - General: 'configuration/components/general.md'
      - Parameters: 'configuration/components/parameters.md'
      - Default Values: 'configuration/components/default_values.md'
      - Inherited Values: 'configuration/components/inherited_values.md'
      - Object Mapping: 'configuration/components/object_mapping.md'
      - Entry Collection: 'configuration/components/entry_collection.md'
    - Configurations:
      - General: 'configuration/configurations/general.md'
      - Defined: 'configuration/configurations/defined.md'
      - Undefined: 'configuration/configurations/undefined.md'
  - Loading:
    - General: 'loading/general.md'
    - Registration: 'loading/registration.md'
    - Instantiation: 'loading/instantiation.md'
  - Example: 'example.md'

site_name: Components.js Documentation

markdown_extensions:
  - admonition

theme: readthedocs
