pages:
  - Home: 'index.md'
  - Getting Started:
    - Installation: 'getting_started/installation.md'

site_name: Components.js Documentation

markdown_extensions:
  - admonition

theme: readthedocs
